trigger:
- master

variables:
  configuration: 'Release'
#  system.debug: 'true'

jobs:
##################################################################################
## LINUX BUILD JOB
- job: buildLinux
  displayName: 'Build Linux binary - $(configuration)'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=$(configuration) ..
    displayName: 'cmake configure'
  
  - task: CMake@1
    inputs:
      cmakeArgs: '--build . --config $(configuration)'
  
  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      contents: '**/primes_in_range'
      targetFolder: '$(build.artifactStagingDirectory)/Linux'
      flattenFolders: true
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'artifact'
      artifactType: 'container'

##################################################################################
## WINDOWS BUILD JOB
- job: buildWindows
  displayName: 'Build Windows binary - $(configuration)'
  pool:
    vmImage: 'windows-latest'
  #variables:
  #  system.debug: 'true'
  steps:
  - script: |
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=$(configuration) ..
    displayName: 'cmake configure'
  
  - task: CMake@1
    inputs:
      cmakeArgs: '--build . --config $(configuration)'
  
  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      contents: '**/primes_in_range.exe'
      targetFolder: '$(build.artifactStagingDirectory)/Windows'
      flattenFolders: true
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'artifact'
      artifactType: 'container'