jobs:
##################################################################################
## LINUX BUILD JOB
- job: buildLinux
  displayName: 'Build Linux binary'
  pool:
    vmImage: 'Ubuntu 16.04'
  #variables:
  #  system.debug: 'true'
  steps:
  - script: |
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release ..
    displayName: 'cmake configure'
  
  - task: CMake@1
    inputs:
      cmakeArgs: '--build . --config Release'
  
  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      contents: '**/primes_in_range'
      targetFolder: '$(build.artifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'artifact'
      artifactType: 'container'

##################################################################################
## WINDOWS BUILD JOB
- job: buildWindows
  displayName: 'Build Windows binary'
  pool:
    vmImage: 'windows-latest'
  #variables:
  #  system.debug: 'true'
  steps:
  - script: |
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release ..
    displayName: 'cmake configure'
  
  - task: CMake@1
    inputs:
      cmakeArgs: '--build . --config Release'
  
  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      contents: '**/primes_in_range.exe'
      targetFolder: '$(build.artifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'artifact'
      artifactType: 'container'